import Head from 'next/head'
import React, { useState, useEffect } from 'react'

import styles from "styles/main/index.module.css"

import { fetchText } from 'src/hooks/fetchText'
import useUserData from 'src/context/useUserData'

import MainSwiper from "src/components/main/MainSwiper"
import Menu from "src/components/main/Menu"
import Program from "src/components/main/Program"


import MenuRoundedIcon from '@mui/icons-material/MenuRounded';
import NotificationsNoneIcon from '@mui/icons-material/NotificationsNone';

const Home = () => {
  const [text, setText] = useState()
  const [scrollY, setScrollY] = useState(0)
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const handleIsMenuOpen = (bool) => { setIsMenuOpen(bool);}
  const { language, setLanguage } = useUserData()

  useEffect(() => {
    const fetchData = async () => {
      try {

        const fetchedText = await fetchText("index", language)
        setText(fetchedText)
      } catch (e) {
        console.log(e)
      }
    }
    fetchData()
  }, [])
  
  //scroll Y 포지션
  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const onMenuClick = () => {
    setIsMenuOpen(true)
  }

  return (
    <div>
      <Head>
        <title>다문화소식</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isMenuOpen &&
        <div className={scrollY === 0 ? styles.header_container : `${styles.header_container} ${styles.add_background}`}>
          <NotificationsNoneIcon />
          <MenuRoundedIcon className={styles.menu_icon} onClick={onMenuClick} />
        </div>
      }
      <Menu isMenuOpen={isMenuOpen} handleIsMenuOpen={handleIsMenuOpen} /> 
      <MainSwiper />

      <Program />
      {/* <div>{text ? text.hi : ""}</div> */}
    </div>
  )
}
export default Home